#CH-230-A
#a7_p3.c
#Flavia Tasellari
#ftasellari@jacobs-university.de

all: use_linked_list

use_linked_list: linked_list.o use_linked_list.o
                 gcc -Wall -o use_linked_list linked_list.o use_linked_list.o

linked_list.o: linked_list.h linked_list.c
               gcc -Wall -c linked_list.c

use_linked_list.o: linked_list.h use_linked_list.c
                   gcc -Wall -c use_linked_list.c

#Delete all generated object files and the executable
clean :
     rm -f use_linked_list *.o